spring.application.name=aula-jwt
spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=MANAGERS

spring.datasource.url=jdbc:mysql://localhost:3306/JwtApp
spring.datasource.username=root
spring.datasource.password=mypassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialeto do MySQL (caso use JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

security.config.prefix=Bearer
security.config.key=SECRET_KEY
security.config.expiration=3600000